version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=abstractions
    ports:
      - 3306:3306
  api:
    build: ../api
    ports:
      - 8080:9443
    environment:
      - DATABASE_HOST=db
  webapp:
    build: ../webapp
    ports:
      - 80:80
      - 443:443
    links:
      - api
