version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=abstractions
    ports:
      - 3306:3306
  api:
    build: ../api
    ports:
      - 8080:8080
  webapp:
    build: ../webapp
    ports:
      - 9000:80
