version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'pixelcorp'
    ports:
      - "3307:3306"
    expose:
      - '3306'
  api:
    restart: always
    build: ../pixelcorp-api-java
    ports:
      - 8080:9443
    expose:
      - '8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pixelcorp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
  webapp:
    build: ../pixelcorp-web
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    # volumes:
    #   - ../pixelcorp-web/dist:/usr/share/nginx/html
