apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
    - name: healthz
      port: 80
  selector:
    app: mysql
  type: NodePort
