apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: stevesloka/abstractions-web
        imagePullPolicy: Always
        ports:
          - name: tls
            containerPort: 443
          - name: standard
            containerPort: 80
