apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: develop,www.develop.local.k8s.com
spec:
  ports:
    - name: tls
      port: 443
    - name: standard
      port: 80
  selector:
    app: web
  type: NodePort
