apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: 192.168.2.50:5000/abstractions-web
        imagePullPolicy: Always
        ports:
          - name: tls
            containerPort: 443
          - name: standard
            containerPort: 80
        volumeMounts:
          - name: web-speakers
            mountPath: /usr/share/nginx/html/assets/data
      volumes:
        - name: web-speakers
          configMap:
            name: web-speakers
