apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: pixelcorp
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
    - name: healthz
      port: 80
  selector:
    app: mysql
  type: ClusterIP

---

apiVersion: v1
data:
  mysql-root-password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: mysql-creds
  namespace: pixelcorp
type: Opaque

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: pixelcorp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
          - name: mysql
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-root-password
          - name: MYSQL_DATABASE
            value: pixelcorp
      - name: mysql-healthz
        image: stevesloka/mysql-healthz:1.0.0
        imagePullPolicy: Always
        ports:
          - name: healthz
            containerPort: 80
        env:
          - name: DATABASE_USERNAME
            value: root
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-root-password
          - name: HTTP_ADDR
            value: "0.0.0.0:80"
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: pixelcorp

---