
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: pixelcorp
  labels:
    app: api
spec:
  ports:
    - name: api
      port: 8080
  selector:
    app: api
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: pixelcorp
  annotations:
    emmie-replace: api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: stevesloka/pixelcorp-api:1.0.0
        imagePullPolicy: Always
        ports:
          - name: api
            containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/pixelcorp
          - name: DATABASE_USERNAME
            value: root
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-root-password
          - name: DATABASE_HOST
            value: mysql
        # readinessProbe:
        #   # an http probe
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   # length of time to wait for a pod to initialize
        #   # after pod startup, before applying health checking
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1

---